---
# tasks file for vitalied.ssh

- name: apt-get install
  apt:
    name: ssh
    state: latest
  tags: vitalied.ssh

- name: configure ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin {{ ssh_permit_root_login }}
  notify: restart ssh
  tags: vitalied.ssh
